inherit_gem:
  makandra-rubocop:
    - config/default.yml
    - config/ext/rails.yml

Bundler/OrderedGems:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
