dist: xenial

language: ruby
rvm:
  - 2.6.5

addons:
  chrome: stable
  postgresql: '10'
  apt:
    packages:
      - chromium-chromedriver

before_install:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - bundle exec bin/setup

script:
  - bundle exec rake spec
  - bundle exec rake cucumber

services:
  - postgresql

cache:
  bundler: true
  yarn: true
