common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: 
  password: 

development:
  <<: *common
  database: wintermute_development

test:
  <<: *common
  database: wintermute_test<%= ENV['TEST_ENV_NUMBER'] %>
