environment: &environment
  secret_key_base: <%= ENV['WINTERMUTE_SECRET_KEY_BASE'] %>
  github_client_id: <%= ENV['WINTERMUTE_GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['WINTERMUTE_GITHUB_CLIENT_SECRET'] %>
  github_personal_access_token: <%= ENV['WINTERMUTE_GITHUB_PERSONAL_ACCESS_TOKEN'] %>

development:
  <<: *environment
  secret_key_base: 4fc5d46e276f535c6955a24a0e6026c620e9fb1061d9c3852456ae42c4c48cc01010f7af8cafca73df61c41e82b9c37ddcb6b786f677f0b77681c3e55cbd8e6d
  errors_controller_basic_password: errors_controller_basic_password

test:
  secret_key_base: 3d12d0348a68222c6745034385443092ff7c702ccea672ab930b0cf7d3ac97f207afd58c8b9d92f24e3ee93b5d9f78c776829d540b0ef830c2f929492e34d968
  github_client_id: some_client_id
  github_client_secret: github_client_secret
  github_personal_access_token: github_personal_access_token
  errors_controller_basic_password: errors_controller_basic_password
